[project]
name = "vonage"
dynamic = ["version"]
description = "Python Server SDK for using Vonage APIs"
readme = "README.md"
authors = [{ name = "Vonage", email = "devrel@vonage.com" }]
requires-python = ">=3.8"
dependencies = [
  "vonage-utils>=1.1.2",
  "vonage-http-client>=1.4.0",
  "vonage-application>=1.0.0",
  "vonage-messages>=1.1.1",
  "vonage-number-insight>=1.0.0",
  "vonage-sms>=1.1.1",
  "vonage-users>=1.1.2",
  "vonage-verify>=1.1.1",
  "vonage-verify-v2>=1.1.2",
  "vonage-voice>=1.0.3",
]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: Apache Software License",
]

[project.urls]
homepage = "https://github.com/Vonage/vonage-python-sdk"

[tool.setuptools.dynamic]
version = { attr = "vonage._version.__version__" }

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
